"""由注册表生成 TerraLID 铅同位素数据录入工作簿（Excel 模板）。

`reference/metadata` 是 TerraLID Metadata Profile（英文字段定义）；考古/冶金用户用 Excel
录数据，Python 负责校验与推导。本脚本把 `Profile` 注册表渲染成一张多工作表工作簿：
表名、列序、列宽与数值格式一律取自 `layout.build_layout()`（唯一真源），本模块负责**录入表**
的写入——双层表头、单元格批注、受控词表下拉、必填条件格式——以及命令行入口。

分工与边界：

- `scripts/entry_workbook_info.py` 负责 README / 0_SCHEMA / 0_VOCAB / 99_CHECK 四张信息表
  （只读它的常量与写入函数，方向单向往外）。
- `data/metadata_profile/io_xlsx.py` 负责**读已填工作簿**与回写校验结果，本脚本只做**生成模板**；
  两者共用 `io_xlsx` 的表头约定（`FIRST_DATA_ROW` / `CHECK_HEADERS`），避免两侧漂移。
- 公开 API 只依赖传入的 `Profile`：不做文件系统搜索、不解析 markdown、不导入 PyQt5；只有
  `main()` 才调 `profile.load_profile()`，因此测试可用 `spec.py` 手工构造的注册表独立验证。

命令行::

    python scripts/build_entry_workbook.py [--output PATH] [--profile-root PATH]
                                           [--emit-json PATH] [--force]

目标已存在时默认拒绝覆盖（用户的工作簿可能已填数据），确认后加 ``--force``。
"""
from __future__ import annotations

import argparse
import inspect
import json
import logging
import re
import sys
from collections.abc import Mapping, Sequence
from io import BytesIO
from pathlib import Path
from types import ModuleType
from typing import Any

from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.formatting.rule import FormulaRule
from openpyxl.styles import PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.workbook.defined_name import DefinedName
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.worksheet.worksheet import Worksheet

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from data.metadata_profile.io_xlsx import FIRST_DATA_ROW  # noqa: E402
from data.metadata_profile.layout import (  # noqa: E402
    DEFAULT_COLUMN_WIDTH,
    GROUP_COLUMN,
    OWNER_SHEET_COLUMN,
    RATIO_HOST_COLUMN,
    ROWS_ID_COLUMN,
    ColumnSpec,
    SheetKind,
    SheetSpec,
    WorkbookLayout,
    build_layout,
    owner_sheet_options,
)
from data.metadata_profile.spec import (  # noqa: E402
    DATE_TYPES,
    DATE_UNITS,
    PROFILE_LICENSE,
    PROFILE_SOURCE,
    RATIO_SOURCES,
    SIGMA_LEVELS,
    YES_NO_UNCLEAR,
    Profile,
    ValueKind,
)
from scripts.entry_workbook_info import (  # noqa: E402
    HEADER_FILL,
    HEADER_FONT,
    OWNER_SHEET_LIST_NAME,
    RATIO_NAME_LIST_NAME,
    SCHEMA_HEADERS,
    group_condition_oid,
    schema_rows,
    write_check_sheet,
    write_readme_sheet,
    write_schema_sheet,
    write_vocab_sheet,
)

logger = logging.getLogger(__name__)

#: 每条录入列的预设数据行数：数值格式 / 下拉 / 条件格式的作用范围。填满后可在 Excel 里
#: 向下拖拽沿用格式（模板不预生成无限行）。
ENTRY_ROW_COUNT = 200

#: 批注框尺寸——openpyxl 默认 144×79 装不下 definition + allowed + example。
COMMENT_WIDTH = 360
COMMENT_HEIGHT = 180
COMMENT_AUTHOR = "IsotopesAnalyse"

#: 受控词表命名区域前缀：命名区域名 = 前缀 + 词表 id。
VOCAB_NAME_PREFIX = "Vocab_"

#: Excel 对内联 list 型数据验证公式的长度上限（字符）。
_INLINE_LIST_CHAR_LIMIT = 255

#: `ratio_host` 列在档案给不出宿主时的兜底取值（A14 样品自身 / A9.3 标样实测）。
_FALLBACK_RATIO_HOSTS: tuple[str, ...] = ("A14", "A9.3")

#: 必填列的红色底（浅红，沿用 Excel"差"样式）。
_REQUIRED_FILL = PatternFill(start_color="FFFFC7CE", end_color="FFFFC7CE", fill_type="solid")

#: TerraLID ID 主键列的批注口径。档案（`Provided by: TerraLID system` + `Allowed values: t.b.d.`）
#: 说这些 ID 由数据库分配，但**本工具不代为生成** —— 不能承诺"可留空"，否则用户留空后
#: 块表/明细行表会无值可挂（它们的 `owner_id` / `parent_id` 正是锚在这里）。
_TERRALID_ID_NOTE = (
    "提示: 档案中该 ID 由 TerraLID 数据库分配（Allowed values 为 t.b.d.）；"
    "本工具不代为生成（not generated by this tool）——"
    "仅当你需要用块表（6_Person … 17_LIA-Ratio）或明细行表（*_Rows）挂接到该行时才必须填写，"
    "且须在同一张表内唯一（unique within the sheet）。"
)

#: 辅助列列宽（16–22）。
_HELPER_WIDTHS: dict[str, int] = {
    OWNER_SHEET_COLUMN: 16,
    "owner_id": 18,
    RATIO_HOST_COLUMN: 17,
    ROWS_ID_COLUMN: 18,
    GROUP_COLUMN: 18,
    "parent_id": 18,
    "site_id": 16,
    "assemblage_id": 20,
    "object_id": 16,
    "sample_id": 16,
}

#: 取值类型 → Excel 内联下拉（档案固定枚举；受控词表另走 `Vocab_*` 命名区域）。
_KIND_LISTS: dict[ValueKind, tuple[str, ...]] = {
    ValueKind.SIGMA: tuple(str(level) for level in SIGMA_LEVELS),
    ValueKind.RATIO_SOURCE: RATIO_SOURCES,
    ValueKind.GEOL_TYPE: DATE_TYPES,
    ValueKind.UNIT_AGE: DATE_UNITS,
    ValueKind.YES_NO_UNCLEAR: YES_NO_UNCLEAR,
}

#: 默认输出目录与档案根目录（相对仓库根）。
DEFAULT_OUTPUT_DIR = ROOT / "数据"
DEFAULT_PROFILE_ROOT = ROOT / "reference" / "metadata"

#: 惰性加载的受控词表模块（`vocab.py` 尚未落地时为 None）。
_vocab_module: ModuleType | None = None
_vocab_module_checked = False


def _load_vocab_module() -> ModuleType | None:
    """延迟导入 `data/metadata_profile/vocab.py`；不可用时记 warning 并回退为"无词表"。"""
    global _vocab_module, _vocab_module_checked
    if _vocab_module_checked:
        return _vocab_module
    _vocab_module_checked = True
    try:
        from data.metadata_profile import vocab as module
    except ImportError as err:
        logger.warning("受控词表模块不可用，将生成无词表的工作簿（下拉为空）: %s", err)
        _vocab_module = None
    else:
        _vocab_module = module
    return _vocab_module


def _normalize_vocab_items(value: Any) -> list[str]:
    """把一条词表定义归一为字符串列表（兼容 `vocab.Vocabulary` 与 ``{id: [...]}``）。"""
    if isinstance(value, str):
        return [value]
    if isinstance(value, Mapping):
        for key in ("terms", "values", "items", "options"):
            if key in value:
                return _normalize_vocab_items(value[key])
        return []
    terms = getattr(value, "terms", None)
    if isinstance(terms, Sequence) and not isinstance(terms, str):
        return [str(item) for item in terms]
    if isinstance(value, Sequence):
        return [str(item) for item in value]
    logger.warning("无法识别的词表定义（%s），按空词表处理: %r", type(value).__name__, value)
    return []


def _is_open_ended(module: ModuleType, value: Any, vocab_id: str) -> bool:
    """判断词表是否开放：优先 `vocab.open_ended()`，其次词表对象上的 ``open_ended``。"""
    checker = getattr(module, "open_ended", None)
    if callable(checker):
        try:
            return bool(checker(vocab_id))
        except Exception as err:  # 词表模块仍在演进：不因它让生成器整体失败
            logger.warning("vocab.open_ended(%s) 调用失败，回退为严格词表: %s", vocab_id, err)
    flag = getattr(value, "open_ended", None)
    if isinstance(flag, bool):
        return flag
    if isinstance(value, Mapping) and "open_ended" in value:
        return bool(value["open_ended"])
    return False


def _vocab_metadata() -> tuple[dict[str, list[str]], dict[str, bool]]:
    """读取词表注册表 → ``(词表 id → 词表项, 词表 id → 是否开放式)``。"""
    module = _load_vocab_module()
    if module is None:
        return {}, {}
    raw = getattr(module, "VOCABULARIES", None)
    if not isinstance(raw, Mapping):
        logger.warning("vocab.VOCABULARIES 不是映射（%s），按无词表处理", type(raw).__name__)
        return {}, {}
    entries: dict[str, list[str]] = {}
    open_ended: dict[str, bool] = {}
    for vocab_id, value in raw.items():
        key = str(vocab_id)
        entries[key] = _normalize_vocab_items(value)
        open_ended[key] = _is_open_ended(module, value, key)
    return entries, open_ended


def _referenced_vocab_ids(profile: Profile) -> list[str]:
    """按布局中的列序返回被引用的词表 id（去重）。"""
    ordered: list[str] = []
    for sheet in build_layout(profile).sheets:
        for column in sheet.columns:
            if column.vocab_id and column.vocab_id not in ordered:
                ordered.append(column.vocab_id)
    return ordered


def vocab_layout(profile: Profile) -> dict[str, list[str]]:
    """受控词表 id → 该词表在 ``0_VOCAB`` 中的列内容（词表项，保持给定顺序）。

    列顺序 = 布局里被引用的先后，再补上 ``vocab.py`` 中未被任何列引用（但仍是档案一部分）
    的词表；被引用却查不到定义的词表也会建列（空列），这样每个 ``Vocab_<id>`` 命名区域
    都能在工作簿里解析。

    Args:
        profile: 注册表（只依赖传入对象，不读文件系统）。

    Returns:
        词表 id → 词表项列表；`vocab.py` 尚不可用时所有值为空列表。
    """
    entries, _ = _vocab_metadata()
    ordered: dict[str, list[str]] = {}
    for vocab_id in _referenced_vocab_ids(profile):
        ordered[vocab_id] = list(entries.get(vocab_id, []))
    for vocab_id, items in entries.items():
        ordered.setdefault(vocab_id, list(items))
    return ordered


def _entry_last_row() -> int:
    """录入列的最后一个预设数据行（1 起）。"""
    return FIRST_DATA_ROW + ENTRY_ROW_COUNT - 1


def _unique_defined_name(base: str, used: set[str]) -> str:
    """把词表 id 变成合法且不重复的 Excel 命名区域名。"""
    safe = re.sub(r"[^0-9A-Za-z_.]", "_", base)
    if safe not in used:
        used.add(safe)
        return safe
    index = 2
    while f"{safe}_{index}" in used:
        index += 1
    unique = f"{safe}_{index}"
    used.add(unique)
    logger.warning("命名区域 %s 已存在，改用 %s", safe, unique)
    return unique


def _vocab_defined_names(vocab: Mapping[str, Sequence[str]]) -> dict[str, str]:
    """词表 id → 命名区域名（`0_VOCAB` 与各录入表的下拉共用同一份映射）。"""
    used: set[str] = {RATIO_NAME_LIST_NAME, OWNER_SHEET_LIST_NAME}
    return {
        vocab_id: _unique_defined_name(f"{VOCAB_NAME_PREFIX}{vocab_id}", used)
        for vocab_id in vocab
    }


def _inline_list_formula(values: Sequence[str]) -> str:
    """Excel 内联下拉公式（``"a,b,c"``）。

    内联取值受 Excel 的 255 字符上限约束，超限时记 warning（缺值比静默截断更容易发现）；
    真超出时应改用命名区域。
    """
    if any("," in value for value in values):
        logger.warning("内联下拉取值含逗号，Excel 可能拆错: %s", list(values))
    formula = '"' + ",".join(values) + '"'
    if len(formula) > _INLINE_LIST_CHAR_LIMIT:
        logger.warning(
            "内联下拉 %d 字符，超过 Excel 上限 %d，部分取值可能不显示: %s",
            len(formula),
            _INLINE_LIST_CHAR_LIMIT,
            list(values)[:6],
        )
    return formula


def _required_formula(
    sheet: SheetSpec,
    column: ColumnSpec,
    column_index: int,
) -> str | None:
    """构造必填列的条件格式公式。

    形态：``AND([COUNTA(<组内各列本行>)>0,]OR(COUNTA(左侧)>0,COUNTA(右侧)>0),ISBLANK(<本列>))``
    —— "本行其它列有值而该列为空"时标红；若该列位于某个**可选分组**内，再加一条分组已启用
    的因子（组内一格未填 → 整组不标红，见 `group_condition_oid`）。该表只有一列时返回 ``None``。

    Note:
        openpyxl 的 ``FormulaRule`` 只接受不带前导 ``=`` 的公式文本。
    """
    row = FIRST_DATA_ROW
    conditions: list[str] = []
    factor = _group_enabled_factor(sheet, column)
    if factor is not None:
        conditions.append(factor)

    sides: list[str] = []
    if column_index > 1:
        before = get_column_letter(column_index - 1)
        sides.append(f"COUNTA($A{row}:${before}{row})>0")
    if column_index < sheet.column_count:
        after = get_column_letter(column_index + 1)
        sides.append(f"COUNTA(${after}{row}:${get_column_letter(sheet.column_count)}{row})>0")
    if not sides:
        return None
    conditions.append(sides[0] if len(sides) == 1 else "OR(" + ",".join(sides) + ")")
    conditions.append(f"ISBLANK({get_column_letter(column_index)}{row})")
    return "AND(" + ",".join(conditions) + ")"


def _group_enabled_factor(sheet: SheetSpec, column: ColumnSpec) -> str | None:
    """可选分组的"已启用"因子：该组在本行列出的任一格有值。

    分组判定走 `layout.ColumnSpec.optional_ancestors`（单一真源）；组内各列由
    `SheetSpec.columns` 的 OID 前缀派生（不写死列字母）；该列不受可选分组限制时返回
    ``None``（真·无条件必填）。
    """
    group_oid = group_condition_oid(column)
    if group_oid is None:
        return None
    prefix = f"{group_oid}."
    offset = len(sheet.helper_columns)
    cells = [
        f"${get_column_letter(index)}{FIRST_DATA_ROW}"
        for index, candidate in enumerate(sheet.columns, start=offset + 1)
        if candidate.oid == group_oid or candidate.oid.startswith(prefix)
    ]
    if not cells:
        return None
    return f"COUNTA({','.join(cells)})>0"


def _is_terralid_id_column(column: ColumnSpec) -> bool:
    """是否为 TerraLID 分配的 ID 列（块表 / 明细行表的挂接锚点）。

    判据取档案语义而非写死 OID：``Provided by: TerraLID system`` 且键名为 ``terralid_*``
    （实测命中 ``SI0`` / ``AS0`` / ``O0`` / ``S0`` / ``A0`` 五列，材料表没有这种列）。
    """
    return column.is_system_provided and column.key.startswith("terralid_")


def _comment_text(column: ColumnSpec) -> str:
    """第 2 行批注文本：定义 / 允许值 / 示例 / 来源（便于回溯 `reference/metadata`）。"""
    lines = [
        f"{column.oid} {column.key}",
        f"中文标签: {column.label_zh}",
        f"英文标签: {column.label_en}",
    ]
    if column.definition:
        lines.append(f"定义: {column.definition}")
    if column.allowed:
        lines.append(f"允许值: {column.allowed}")
    if column.example:
        lines.append(f"示例: {column.example}")
    if column.vocab_id:
        lines.append(f"受控词表: {column.vocab_id}（完整取值见 0_VOCAB 表）")
    lines.append(f"来源: {column.source_doc}:{column.source_line}")
    if _is_terralid_id_column(column):
        # 档案说由系统分配，但本工具不生成 —— 不能写"可留空"
        lines.append(_TERRALID_ID_NOTE)
    elif column.is_system_provided:
        lines.append("提示: 该列由工具自动补齐，可留空。")
    elif column.is_required_from_provider:
        lines.append("提示: 必填；同一行有其它内容而此列为空时会被标红。")
    return "\n".join(lines)


def _add_list_validation(
    worksheet: Worksheet,
    column_index: int,
    formula1: str,
    *,
    strict: bool,
    prompt: str | None = None,
) -> None:
    """给一列的数据行加下拉；``strict=False`` 时允许自由文本（开放词表）。"""
    validation = DataValidation(
        type="list", formula1=formula1, allow_blank=True, showErrorMessage=strict
    )
    if strict:
        validation.errorStyle = "stop"
        validation.errorTitle = "取值不在受控范围内"
        validation.error = "该字段为受控取值：请从下拉列表中选择，完整词表见 0_VOCAB 表。"
    if prompt:
        validation.showInputMessage = True
        validation.promptTitle = "允许自由文本"
        validation.prompt = prompt
    letter = get_column_letter(column_index)
    validation.add(f"{letter}{FIRST_DATA_ROW}:{letter}{_entry_last_row()}")
    worksheet.add_data_validation(validation)


def _ratio_host_values(sheet: SheetSpec) -> tuple[str, ...]:
    """``ratio_host`` 允许的取值：档案给出的 B6 宿主字段 OID。"""
    return sheet.host_oids or _FALLBACK_RATIO_HOSTS


def _group_values(sheet: SheetSpec) -> tuple[str, ...]:
    """明细行表 ``group`` 允许的取值：该表承载的组根字段 OID（取自布局，不自行推断）。"""
    return sheet.host_oids


def _write_entry_sheet(
    worksheet: Worksheet,
    sheet: SheetSpec,
    *,
    vocab_names: Mapping[str, str],
    open_ended: Mapping[str, bool],
) -> None:
    """写一张录入表：双层表头、列宽、数值格式、批注、下拉与必填条件格式。"""
    for index, (key, label) in enumerate(
        zip(sheet.all_header_keys, sheet.all_header_labels), start=1
    ):
        head = worksheet.cell(row=1, column=index, value=key)
        head.font = HEADER_FONT
        head.fill = HEADER_FILL
        worksheet.cell(row=2, column=index, value=label).font = HEADER_FONT
    worksheet.freeze_panes = f"A{FIRST_DATA_ROW}"

    widths = [_HELPER_WIDTHS.get(name, DEFAULT_COLUMN_WIDTH) for name in sheet.helper_columns]
    widths.extend(column.width for column in sheet.columns)
    for index, width in enumerate(widths, start=1):
        worksheet.column_dimensions[get_column_letter(index)].width = width

    # 辅助列：owner_sheet 用实体表 + 明细行表命名区域，ratio_host 用档案给出的两个宿主字段，
    # group 用该明细行表承载的组根 OID（两者都直接取布局给出的 host_oids）。
    for index, name in enumerate(sheet.helper_columns, start=1):
        if name == OWNER_SHEET_COLUMN:
            _add_list_validation(worksheet, index, f"={OWNER_SHEET_LIST_NAME}", strict=True)
        elif name == RATIO_HOST_COLUMN:
            _add_list_validation(
                worksheet, index, _inline_list_formula(_ratio_host_values(sheet)), strict=True
            )
        elif name == GROUP_COLUMN:
            groups = _group_values(sheet)
            if groups:
                _add_list_validation(
                    worksheet, index, _inline_list_formula(groups), strict=True
                )
            else:
                logger.warning("明细行表 %s 没有组根 OID，已跳过 group 下拉", sheet.name)

    offset = len(sheet.helper_columns)
    for position, column in enumerate(sheet.columns):
        index = offset + position + 1
        worksheet.cell(row=2, column=index).comment = Comment(
            _comment_text(column),
            COMMENT_AUTHOR,
            height=COMMENT_HEIGHT,
            width=COMMENT_WIDTH,
        )
        if column.number_format:
            for row in range(FIRST_DATA_ROW, _entry_last_row() + 1):
                worksheet.cell(row=row, column=index).number_format = column.number_format

        kind_values = _KIND_LISTS.get(column.value_kind)
        defined_name = vocab_names.get(column.vocab_id) if column.vocab_id else None
        if kind_values is not None:
            _add_list_validation(
                worksheet, index, _inline_list_formula(kind_values), strict=True
            )
        elif column.value_kind is ValueKind.RATIO_NAME:
            _add_list_validation(worksheet, index, f"={RATIO_NAME_LIST_NAME}", strict=True)
        elif defined_name is not None:
            is_open = bool(open_ended.get(column.vocab_id, False))
            _add_list_validation(
                worksheet,
                index,
                f"={defined_name}",
                strict=not is_open,
                prompt="档案说明该词表可能不全，可填写词表之外的取值。" if is_open else None,
            )
        elif column.vocab_id:
            logger.warning("词表 %s 没有命名区域，已跳过下拉", column.vocab_id)
        elif column.value_kind is ValueKind.CONTROLLED_VOCAB:
            logger.warning("受控取值列 %s 没有 vocab_id，已跳过下拉", column.qualified_key)

        if column.is_required_from_provider:
            formula = _required_formula(sheet, column, index)
            if formula is not None:
                letter = get_column_letter(index)
                worksheet.conditional_formatting.add(
                    f"{letter}{FIRST_DATA_ROW}:{letter}{_entry_last_row()}",
                    FormulaRule(formula=[formula], fill=_REQUIRED_FILL, stopIfTrue=False),
                )


def _build_workbook(profile: Profile) -> Workbook:
    """按 `layout.build_layout()` 的顺序构建工作簿对象（内存态）。

    批注尺寸、命名区域等在内存对象上才完整（openpyxl 往返不保留批注框尺寸），因此核对
    批注的测试应使用本函数而不是 ``workbook_bytes()`` 的读回结果。
    """
    layout = build_layout(profile)
    vocab = vocab_layout(profile)
    vocab_names = _vocab_defined_names(vocab)
    _, open_ended = _vocab_metadata()
    rows = schema_rows(profile)

    workbook = Workbook()
    workbook.remove(workbook.active)
    for sheet in layout.sheets:
        if sheet.name in workbook.sheetnames:
            raise ValueError(f"布局里出现重名工作表: {sheet.name}")
        worksheet = workbook.create_sheet(title=sheet.name)
        if sheet.kind is SheetKind.README:
            write_readme_sheet(worksheet, layout, profile)
        elif sheet.kind is SheetKind.SCHEMA:
            write_schema_sheet(worksheet, rows)
        elif sheet.kind is SheetKind.VOCAB:
            write_vocab_sheet(
                workbook, worksheet, vocab, vocab_names, owner_sheet_options(layout)
            )
        elif sheet.kind is SheetKind.CHECK:
            write_check_sheet(worksheet)
        else:
            _write_entry_sheet(
                worksheet,
                sheet,
                vocab_names=vocab_names,
                open_ended=open_ended,
            )
    logger.info(
        "Built workbook: %d sheets, %d schema rows, %d vocabularies",
        len(layout.sheets),
        len(rows),
        len(vocab),
    )
    return workbook


def workbook_bytes(profile: Profile) -> bytes:
    """在内存里生成工作簿并返回 xlsx 字节（供测试与预览）。

    Args:
        profile: 注册表。

    Returns:
        xlsx 文件字节。
    """
    buffer = BytesIO()
    _build_workbook(profile).save(buffer)
    return buffer.getvalue()


def _save_atomically(workbook: Workbook, path: Path) -> Path:
    """以"临时文件 + 原子替换"落盘，避免中途失败留下半截 xlsx。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    try:
        workbook.save(temporary)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)
    return path


def build_workbook(profile: Profile, output: str | Path) -> Path:
    """生成录入工作簿并落盘。

    Args:
        profile: 注册表（只依赖传入对象，不做文件系统搜索）。
        output: 输出 xlsx 路径；父目录不存在时自动创建。

    Returns:
        实际写入的路径。

    Raises:
        OSError: 目录不可写或磁盘写入失败。
        ValueError: 布局里有重名工作表。
    """
    path = _save_atomically(_build_workbook(profile), Path(output))
    logger.info("Entry workbook written: %s", path)
    return path


def registry_snapshot(
    profile: Profile,
    layout: WorkbookLayout,
    vocab: Mapping[str, Sequence[str]],
) -> dict[str, Any]:
    """把注册表（表/字段/词表）序列化为可回归比对的 JSON 结构。"""
    return {
        "profile_version": profile.version,
        "profile_source": PROFILE_SOURCE,
        "profile_license": PROFILE_LICENSE,
        "sheet_count": len(layout.sheets),
        "schema_row_count": len(schema_rows(profile)),
        "sheets": [
            {
                "name": sheet.name,
                "kind": sheet.kind.value,
                "table": sheet.table,
                "title_zh": sheet.title_zh,
                "title_en": sheet.title_en,
                "helper_columns": list(sheet.helper_columns),
                "host_oids": list(sheet.host_oids),
                "columns": [
                    {
                        "oid": column.oid,
                        "key": column.key,
                        "label_zh": column.label_zh,
                        "obligation": column.obligation.value,
                        "value_kind": column.value_kind.value,
                        "vocab_id": column.vocab_id,
                        "number_format": column.number_format,
                        "width": column.width,
                        "is_system_provided": column.is_system_provided,
                        "is_required_from_provider": column.is_required_from_provider,
                    }
                    for column in sheet.columns
                ],
            }
            for sheet in layout.sheets
        ],
        "vocabularies": {vocab_id: list(items) for vocab_id, items in vocab.items()},
    }


def _write_registry_json(snapshot: Mapping[str, Any], path: Path) -> Path:
    """把注册表快照写成 JSON（UTF-8，缩进 2）。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    logger.info("Registry snapshot written: %s", path)
    return path


def _load_profile(profile_root: Path) -> Profile:
    """调用解析器加载注册表（生成器自身不解析 markdown）。

    Args:
        profile_root: 档案根目录（含 `docs/` 与 `includes/`）。

    Returns:
        解析好的注册表。

    Raises:
        RuntimeError: 解析器模块或 `load_profile()` 尚不可用。
    """
    try:
        from data.metadata_profile import profile as profile_module
    except ImportError as err:
        raise RuntimeError("注册表解析器 data/metadata_profile/profile.py 尚未就绪") from err
    loader = getattr(profile_module, "load_profile", None)
    if not callable(loader):
        raise RuntimeError("data/metadata_profile/profile.py 未提供 load_profile()")
    if inspect.signature(loader).parameters:
        return loader(profile_root)
    return loader()


def main(argv: Sequence[str] | None = None) -> int:
    """命令行入口。

    Args:
        argv: 参数序列（``None`` 时取 ``sys.argv[1:]``），便于测试注入。

    Returns:
        进程退出码：0 成功；1 失败或拒绝覆盖已存在的目标。
    """
    parser = argparse.ArgumentParser(
        description="由 TerraLID 元数据档案生成铅同位素数据录入工作簿（Excel 模板）。"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="输出 xlsx 路径（缺省 数据/entry_template_TerraLID_v<版本>.xlsx）",
    )
    parser.add_argument(
        "--profile-root",
        type=Path,
        default=DEFAULT_PROFILE_ROOT,
        help="TerraLID 档案根目录（缺省 reference/metadata）",
    )
    parser.add_argument(
        "--emit-json",
        type=Path,
        default=None,
        help="额外把注册表（表/字段/词表）序列化为 JSON，供回归比对",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="目标已存在时覆盖（缺省拒绝，避免覆盖已填写数据的工作簿）",
    )
    args = parser.parse_args(argv)

    try:
        profile = _load_profile(args.profile_root)
    except Exception as err:  # 解析器未就绪 / 档案不可读：CLI 边界统一报错
        logger.exception("Failed to load TerraLID profile: %s", err)
        print(f"加载注册表失败：{err}")
        return 1

    output = (
        args.output
        if args.output is not None
        else DEFAULT_OUTPUT_DIR / f"entry_template_TerraLID_v{profile.version}.xlsx"
    )
    if output.exists() and not args.force:
        logger.warning("Workbook already exists, refusing to overwrite: %s", output)
        print(f"目标文件已存在，未覆盖：{output}")
        print("  该工作簿可能已填写数据；确认后可加 --force 覆盖，或用 --output 指定新路径。")
        return 1

    try:
        path = build_workbook(profile, output)
        layout = build_layout(profile)
        vocab = vocab_layout(profile)
        rows = schema_rows(profile)
        if args.emit_json is not None:
            _write_registry_json(registry_snapshot(profile, layout, vocab), args.emit_json)
    except (OSError, ValueError) as err:
        logger.error("Failed to build entry workbook: %s", err)
        print(f"生成工作簿失败：{err}")
        return 1

    print(f"已生成录入工作簿：{path}")
    print(f"  工作表 {len(layout.sheets)} 张 / 录入字段 {len(rows)} 条 / 受控词表 {len(vocab)} 个")
    if args.emit_json is not None:
        print(f"  注册表 JSON：{args.emit_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "ENTRY_ROW_COUNT",
    "SCHEMA_HEADERS",
    "build_workbook",
    "main",
    "registry_snapshot",
    "schema_rows",
    "vocab_layout",
    "workbook_bytes",
]
