"""录入工作簿的前置/后置信息表：内容生成、文案与写入函数。

`README`（使用说明）、`0_SCHEMA`（字段定义）、`0_VOCAB`（受控词表）、`99_CHECK`（校验报告）
四张表不承载录入字段，只承载"说明与登记"内容，因此与录入表的写入逻辑分开：

- 本模块负责这四张表 + 它们的常量（表头、列宽、样式、README 文案模板），并负责
  `0_SCHEMA` 的行内容 `schema_rows()` 与"最小填写路径"的注册表推导；
- `scripts/build_entry_workbook.py` 负责录入表（双层表头、批注、下拉、必填条件格式）
  与命令行入口，并**单向**导入本模块。

`99_CHECK` 的表头直接从 `data/metadata_profile/io_xlsx.py` 取（与导入器共用一份约定），
不在这里另抄一份字符串，避免两侧漂移。
"""
from __future__ import annotations

import logging
from collections.abc import Mapping, Sequence

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import absolute_coordinate, get_column_letter, quote_sheetname
from openpyxl.workbook.defined_name import DefinedName
from openpyxl.worksheet.worksheet import Worksheet

from data.metadata_profile.io_xlsx import CHECK_FIRST_DATA_ROW, CHECK_HEADERS
from data.metadata_profile.layout import (
    OWNER_SHEET_COLUMN,
    RATIO_HOST_COLUMN,
    ColumnSpec,
    SheetKind,
    SheetSpec,
    WorkbookLayout,
    owner_sheet_options,
)
from data.metadata_profile.spec import (
    LIA_RATIO_NAMES,
    PROFILE_LICENSE,
    PROFILE_SOURCE,
    Block,
    FieldSpec,
    Profile,
    TableKey,
    TableSpec,
    ValueKind,
)

logger = logging.getLogger(__name__)

#: `0_VOCAB` 第 1 行放"词表 id + 中文名"，数据从第 2 行开始。
VOCAB_FIRST_DATA_ROW = 2

#: `0_VOCAB` 里的两列**系统清单**（不是档案词表，但同样以下拉方式提供）。
RATIO_NAME_LIST_NAME = "LIA_Ratio_Names"
OWNER_SHEET_LIST_NAME = "Owner_Sheets"

#: 表头样式（录入表与本模块共用）。
HEADER_FILL = PatternFill(start_color="FFEFEFEF", end_color="FFEFEFEF", fill_type="solid")
HEADER_FONT = Font(bold=True)
_TITLE_FONT = Font(bold=True, size=14)
_SECTION_FONT = Font(bold=True, size=11)
_BODY_FONT = Font()
_TOP_ALIGN = Alignment(vertical="top")

#: `0_SCHEMA` 的列（顺序固定；内联块的宿主并入"所属模块"列，见 `schema_rows()`）。
SCHEMA_HEADERS: tuple[str, ...] = (
    "字段ID",
    "键名",
    "中文标签",
    "英文标签",
    "所属模块",
    "级别",
    "出现次数",
    "提供方",
    "取值类型",
    "受控词表",
    "定义",
    "允许值",
    "示例",
    "源文档",
    "源行号",
)

#: `0_SCHEMA` / `99_CHECK` 列宽（分别与 SCHEMA_HEADERS / CHECK_HEADERS 一一对应）。
SCHEMA_WIDTHS: tuple[int, ...] = (10, 34, 18, 30, 22, 12, 10, 26, 16, 20, 70, 40, 24, 30, 9)
CHECK_WIDTHS: tuple[int, ...] = (12, 18, 16, 34, 60, 20)

#: B6 两个宿主字段的中文说明（README 用；其余宿主按 OID 原样列出）。
RATIO_HOST_LABELS: dict[str, str] = {
    "A14": "样品/器物自身实测比值 analysis_lia_ratio",
    "A9.3": "标样实测比值 analysis_lia_standard-pb_measured",
}

#: `ratio_host` 列在档案给不出宿主时的兜底取值（A14 样品自身 / A9.3 标样实测）。
FALLBACK_RATIO_HOSTS: tuple[str, ...] = ("A14", "A9.3")

#: README 文案模板（``# `` 开头的是小节标题；生成物内容，不走 `translate()`）。
README_TEMPLATE = """TerraLID 铅同位素数据录入工作簿 / Lead Isotope Data Entry Workbook
档案来源: {source}（TerraLID Metadata Profile v{version}，{license}）—— 本工作簿由该档案自动生成。

# 零、最小填写路径（minimum viable entry）
  先看这里：全表的字段里真正必须填的只有几格，其余留空不会报错。
  · 绝对最小（2 张表）：{minimal_analysis}；{minimal_ratio}。{pk_note} ——
    其余 {other_sheet_count} 张录入表可以全部留空：校验 0 error，导入时会自动补齐 5 个派生比值与 A15 模式年龄。
  · 推荐最小（5 张表）：再加 {recommended}。
  · 条件必填（分组规则）：档案把经纬度、四至范围、重量、尺寸、信号强度这类内容放进“可选分组”（0–1 / 0–n）。
    组内【任意一格】填了值，该组的必填项才全部生效（只填西边界、不填其余三边仍会报缺）；整组留空则不作要求，
    红底也遵守这条规则。
  · 先不用管：0_SCHEMA / 0_VOCAB / 99_CHECK 是生成物；表名以 _Rows 结尾的明细行表只在一条记录需要多组值时用；
    11_Ore … 16_ByProducts 只在 O12 Material 指定该材质时才有意义。
  · 例外的必填容器：A9 参考物质（Pb 标样）与 SI5 地理位置是 occurrence=1 的必填容器，组内必填项
    （A9.1 标样名、SI5.3 描述等）不受上面的可选分组豁免。工具不会因为 {a9_rows_sheet} 一行都没有而报错
    （1–n 这类“至少出现一次”的约束只在表内存在行时才可校验），但档案要求每个分析至少有一个 Pb 标准物质：
    建议在 {a9_rows_sheet} 里用 group=A9 补一行标样。
  · 填完必须跑校验（validation），问题逐条写进 99_CHECK；红底只是提醒，最终以 99_CHECK 为准。

# 一、哪些表不能手改（generated sheets）
  1. 表名、列序、字段定义全部由 reference/metadata 档案决定，请勿增删列或改名。
  2. 生成物表（勿手改，校验/导入时会被重写）：0_SCHEMA（字段定义）、0_VOCAB（受控词表）、
     99_CHECK（校验报告）；手改其中的内容会丢失。
  3. 其余各表由你填写：第 1 行是机器键名（ID key，勿改动），第 2 行是中文标签 + 必填标记。
  4. 一条记录占一行；一格里不要用逗号塞多个值 —— 可重复的内容请另起一行（见第三节）。

# 二、实体链路与主外键（entity chain / foreign keys）
  Site 遗址/矿区 → Assemblage 堆积单位 → Object 器物 → Sample 样品 → Analysis 分析
  · 主键（TerraLID ID）：1_Site 的 SI0、2_Assemblage 的 AS0、3_Object 的 O0、4_Sample 的 S0、
    5_Analysis 的 A0。档案里这些 ID 由 TerraLID 数据库分配（Allowed values 为 t.b.d.），
    【本工具不代为生成】（not generated by this tool）：只有当你需要用块表（6_Person …
    17_LIA-Ratio）或明细行表（*_Rows）挂接到该行时才必须填写，且须在同一张表内唯一。
    留空本身不报错，但该行无法被引用（校验会以 warning 提示）。
  · 父外键列（表头第 1 行给出的 helper 列）：assemblage 填 site_id，object 填 assemblage_id，
    sample 填 object_id，analysis 填 sample_id —— 值就是父表那一行的主键值。
  · 档案允许 Object / Analysis 跨级直挂 Site，所以父键是默认建议而非硬约束；但每个子行都
    必须能追溯到一条父行，否则校验会报孤立记录。
  · 材料专属表（11_Ore … 16_ByProducts）按 5_Analysis 的 O12 Material 取值分派，统一挂 object_id。

# 三、可重复块与明细行为什么独立成表（repeatable blocks & detail rows）
  · 人员(B1 Person)、保存与可获取性(B2 Status)、年代(B3 Dating)、化学组成(B4 Chemistry)、
    关联资源(B5 Relation)、铅同位素比值(B6 LIA ratio) 在档案里是“可复用块”：一条记录可以有
    0–n / 1–n 组，无法拍平进一行，因此每块一张长表：{blocks}
  · 块表前两列声明归属：owner_sheet = 宿主表名（下拉：{owner_sheets}），owner_id = 宿主行的
    主键值。例：给 4_Sample 的 S12 填两条比值 → 两行都写 owner_sheet=4_Sample、owner_id=S12。
    漏填这两列的行无法归属到任何记录，校验会直接报错。
  · 主表一行一条记录；主表内可重复的字段组（如遗址的多个坐标点、器物的一组标识符）汇总到
    该模块的“明细行”表（表名以 _Rows 结尾，本工作簿 {row_count} 张）：parent_id = 所属主表那
    一行的主键，group = 该行属于哪个重复组（下拉给出本表的组根 OID），row_id = 该明细行自身
    的 ID。块表要挂到某个明细行时，owner_sheet 选该 _Rows 表、owner_id 填它的 row_id。

# 四、17_LIA-Ratio 的 ratio_host 两种取值
  · {ratio_hosts}。
  · 两者共用同一套 B6 字段，所以必须用 ratio_host 区分“样品自身”与“标样实测”；漏填会判为
    归属不明。

# 五、必填标记与红底（required markers）
  · 第 2 行标签末尾的标记：★ 必填(mandatory) / ☆ 建议(recommended) / · 可选(optional)。
  · 红底条件格式只作用于“必填且须由录入者提供”的列：同一行里其它列有内容、而该列为空时标红。
  · 由工具自动补齐的列（如 B6.7 比值来源 source，系统会填 original / calculated）不会标红，
    可以留空。注意这不适用于上文的主键（TerraLID ID）列：它们同样不标红，但工具【不会】代填，
    需要挂接时必须自己填。
  · 填完必须跑校验：问题会逐条写进 99_CHECK（severity / sheet / record_id / column / message /
    value），修正后再次校验，直到没有 ★ 级问题再交付；红格只是提醒，最终以 99_CHECK 为准。

字段定义/允许值/示例与档案行号见 0_SCHEMA；受控词表取值见 0_VOCAB。
"""


def _range_ref(worksheet: Worksheet, first_row: int, last_row: int, column: int) -> str:
    """单元格区域的绝对引用（含工作表名，供命名区域使用）。"""
    letter = get_column_letter(column)
    coordinates = f"{letter}{first_row}:{letter}{max(last_row, first_row)}"
    return f"{quote_sheetname(worksheet.title)}!{absolute_coordinate(coordinates)}"


def _write_simple_header(
    worksheet: Worksheet, headers: Sequence[str], widths: Sequence[int]
) -> None:
    """写单层表头（加粗 + 浅灰底）并设置列宽。"""
    for index, header in enumerate(headers, start=1):
        cell = worksheet.cell(row=1, column=index, value=header)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
    for index, width in enumerate(widths, start=1):
        worksheet.column_dimensions[get_column_letter(index)].width = width


def write_schema_sheet(worksheet: Worksheet, rows: Sequence[Sequence[object]]) -> None:
    """写 `0_SCHEMA`：字段定义总表（冻结首行 + 自动筛选）。"""
    _write_simple_header(worksheet, SCHEMA_HEADERS, SCHEMA_WIDTHS)
    for row_index, row in enumerate(rows, start=2):
        for column_index, value in enumerate(row, start=1):
            worksheet.cell(row=row_index, column=column_index, value=value)
    worksheet.freeze_panes = "A2"
    last = get_column_letter(len(SCHEMA_HEADERS))
    worksheet.auto_filter.ref = f"A1:{last}{max(1, len(rows) + 1)}"


def write_check_sheet(worksheet: Worksheet) -> None:
    """写 `99_CHECK` 表头（列与顺序取自 `io_xlsx`，与导入器共用一份约定）。"""
    _write_simple_header(worksheet, CHECK_HEADERS, CHECK_WIDTHS)
    worksheet.freeze_panes = f"A{CHECK_FIRST_DATA_ROW}"


def _block_hosts(table: TableSpec) -> dict[Block, list[str]]:
    """模块内每个可复用块 → 去重后的宿主字段 OID（保持出现顺序）。"""
    hosts: dict[Block, list[str]] = {}
    for spec in table.fields:
        if spec.block is None or not spec.block_owner:
            continue
        bucket = hosts.setdefault(spec.block, [])
        if spec.block_owner not in bucket:
            bucket.append(spec.block_owner)
    for block in dict.fromkeys(table.inlined_blocks):
        declared = table.inlined_blocks.count(block)
        found = hosts.get(block, [])
        if len(found) < declared:
            logger.warning(
                "模块 %s 内联 %s 共 %d 次，但只解析出 %d 个宿主（%s）：0_SCHEMA 可能少行",
                table.key.value,
                block.value,
                declared,
                len(found),
                found,
            )
    return hosts


def _block_fields(table: TableSpec, block: Block) -> list[FieldSpec]:
    """模块内某可复用块的字段（按 OID 去重，文档顺序）。"""
    collected: dict[str, FieldSpec] = {}
    for spec in table.fields:
        if spec.block is block and spec.oid not in collected:
            collected[spec.oid] = spec
    return sorted(collected.values(), key=lambda spec: (spec.depth, spec.order))


def _schema_row(spec: FieldSpec, host: str) -> list[object]:
    """一个字段在 ``0_SCHEMA`` 里的行内容（列序同 `SCHEMA_HEADERS`）。"""
    return [
        spec.oid,
        spec.key,
        spec.label_zh or spec.label_en,
        spec.label_en,
        f"{spec.table.value} @ {host}" if host else spec.table.value,
        spec.obligation.value,
        spec.occurrence.value,
        ", ".join(provider.value for provider in spec.provided_by),
        spec.value_kind.value,
        spec.vocab_id or "",
        spec.definition,
        spec.allowed,
        spec.example,
        spec.source_doc,
        spec.source_line,
    ]


def schema_rows(profile: Profile) -> list[list[object]]:
    """``0_SCHEMA`` 的数据行（不含表头）。

    口径 = ``sum(len(table.fields) for table in profile.tables)``：模块自有字段一行，内联块
    字段**按宿主各一行**，因此同一个 B6.1 会在 ``analyses`` 里因 A9.3 / A14 两个宿主出现两次
    （`TableSpec.fields` 本就按内联副本逐条记录，故两者数量相等）。表头里没有单独的"宿主"列
    （列序是固定契约），宿主并入"所属模块"列，形如 ``analyses @ A9.3``。

    Args:
        profile: 注册表。

    Returns:
        行列表；列序与 :data:`SCHEMA_HEADERS` 一致。
    """
    rows: list[list[object]] = []
    for table in profile.tables:
        seen_own: set[str] = set()
        for spec in table.fields:
            if spec.block is not None or spec.oid in seen_own:
                continue
            seen_own.add(spec.oid)
            rows.append(_schema_row(spec, ""))
        for block, hosts in _block_hosts(table).items():
            for host in hosts:
                for spec in _block_fields(table, block):
                    rows.append(_schema_row(spec, host))
    return rows


# ── 必填口径与"最小填写路径"的注册表推导 ──────────────────────────────────


def group_condition_oid(column: ColumnSpec) -> str | None:
    """该列**最近的**可选分组祖先 OID；没有则 ``None``（真·无条件必填）。

    单一真源：直接用 `ColumnSpec.optional_ancestors`（自近及远、由 `layout.py` 判定），
    不再自行按 ``occurrence`` 重算 —— 否则校验侧与红底条件各算一份，档案调整
    ``occurrence`` 时会悄悄漂移。取最近而非最外层：``SI5.1.1`` 的条件来自 ``SI5.1``
    （其列只有 ``SI5.1.1``/``SI5.1.2``），用 ``SI5`` 会把"填了四至范围"误判成"点位组已启用"。

    跳过可复用块的**块根**（``B1``…``B6``）：块表的一行本身就是"用了这一组"的声明
    （由 ``owner_sheet`` / ``owner_id`` 定位），块根不该成为"组已启用"的条件 —— 否则
    ``B6.1`` 的因子会变成 ``COUNTA(B6.1..B6.7)>0`` 的自我指涉，空的比值行永远不标红。
    块内部的嵌套可选组（如 ``B1.4`` 人员 PID）仍照常作为因子。
    """
    block_oids = {column.block.value} if column.block is not None else set()
    return next(
        (ancestor for ancestor in column.optional_ancestors if ancestor not in block_oids),
        None,
    )


def unconditional_required_oids(sheet: SheetSpec) -> list[str]:
    """必填且**不受可选分组限制**的列 OID（含必填容器内的字段，如 ``A6.1``）。"""
    return [
        column.oid
        for column in sheet.columns
        if column.is_required_from_provider and group_condition_oid(column) is None
    ]


def plain_required_oids(sheet: SheetSpec) -> list[str]:
    """必填且不属于**任何**非列祖先的列 OID（连必填容器也没有，如 ``SI1``）。"""
    column_oids = {column.oid for column in sheet.columns}
    return [
        column.oid
        for column in sheet.columns
        if column.is_required_from_provider
        and not [a for a in column.ancestors if a not in column_oids]
    ]


def chain_entity_sheets(layout: WorkbookLayout) -> list[SheetSpec]:
    """Site → Assemblage → Object → Sample → Analysis 链上的实体表（按层级顺序）。"""
    sheets: list[SheetSpec] = []
    key: TableKey | None = TableKey.ANALYSIS
    while key is not None:
        sheet = layout.sheet_for_table(key)
        if sheet is not None:
            sheets.append(sheet)
        key = key.parent
    return list(reversed(sheets))


def write_vocab_sheet(
    workbook: Workbook,
    worksheet: Worksheet,
    vocab: Mapping[str, list[str]],
    names: Mapping[str, str],
    owner_options: Sequence[str],
) -> None:
    """写 `0_VOCAB`：每张词表一列 + 两列系统清单，并建立命名区域。"""
    labels = _vocab_display_names()
    columns: list[tuple[str, list[str], str]] = [
        (f"{vocab_id} {labels.get(vocab_id, '')}".strip(), list(items), names[vocab_id])
        for vocab_id, items in vocab.items()
    ]
    columns.append(
        (
            f"{ValueKind.RATIO_NAME.value} 铅同位素比值（系统清单）",
            list(LIA_RATIO_NAMES),
            RATIO_NAME_LIST_NAME,
        )
    )
    columns.append(
        (f"{OWNER_SHEET_COLUMN} 所属表（系统清单）", list(owner_options), OWNER_SHEET_LIST_NAME)
    )

    for index, (header, items, defined_name) in enumerate(columns, start=1):
        cell = worksheet.cell(row=1, column=index, value=header)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        for offset, item in enumerate(items):
            worksheet.cell(row=VOCAB_FIRST_DATA_ROW + offset, column=index, value=item)
        workbook.defined_names.add(
            DefinedName(
                defined_name,
                attr_text=_range_ref(
                    worksheet,
                    VOCAB_FIRST_DATA_ROW,
                    VOCAB_FIRST_DATA_ROW + len(items) - 1,
                    index,
                ),
            )
        )
        longest = max((len(str(item)) for item in items), default=8)
        worksheet.column_dimensions[get_column_letter(index)].width = min(
            40, max(18, longest + 2)
        )
    worksheet.freeze_panes = f"A{VOCAB_FIRST_DATA_ROW}"


def _vocab_display_names() -> dict[str, str]:
    """词表 id → 中文名（`vocab.py` 提供时使用，缺省只有 id）。"""
    try:
        from data.metadata_profile import vocab as module
    except ImportError as err:
        logger.warning("受控词表模块不可用，0_VOCAB 表头只写词表 id: %s", err)
        return {}
    raw = getattr(module, "VOCABULARIES", None)
    if not isinstance(raw, Mapping):
        return {}
    names: dict[str, str] = {}
    for vocab_id, value in raw.items():
        label = getattr(value, "label_zh", None)
        if isinstance(value, Mapping):
            label = value.get("label_zh", label)
        if label:
            names[str(vocab_id)] = str(label)
    return names


def _format_column_list(sheet: SheetSpec, oids: Sequence[str]) -> str:
    """``OID（中文标签）`` 列表；标签缺失时只写 OID。"""
    parts: list[str] = []
    for oid in oids:
        column = sheet.column(oid)
        label = (column.label_zh or column.label_en) if column is not None else ""
        parts.append(f"{oid}（{label}）" if label else oid)
    return "、".join(parts)


def _minimal_entry_text(layout: WorkbookLayout, profile: Profile) -> dict[str, str]:
    """「零、最小填写路径」的文案取值 —— 全部由注册表现在算，不写死列名清单。"""
    chain = chain_entity_sheets(layout)
    analysis_sheet = chain[-1] if chain else layout.sheet_for_table(TableKey.ANALYSIS)
    ratio_sheet = layout.sheet_for_block(Block.LIA_RATIO)

    minimal_analysis = ""
    if analysis_sheet is not None:
        required = unconditional_required_oids(analysis_sheet)
        minimal_analysis = f"{analysis_sheet.name} 填 {_format_column_list(analysis_sheet, required)}"
    minimal_ratio = ""
    if ratio_sheet is not None:
        required = unconditional_required_oids(ratio_sheet)
        helpers = " / ".join(ratio_sheet.helper_columns)
        minimal_ratio = (
            f"{ratio_sheet.name} 每行填 {helpers} + {_format_column_list(ratio_sheet, required)}"
        )

    key_oids = [
        column.oid
        for sheet in chain
        for column in sheet.columns
        if column.key.startswith("terralid_")
    ]
    pk_note = (
        f"各行主键（{'/'.join(key_oids)}，TerraLID ID）只有在该行需要被块表或明细行表挂接时才填"
        if key_oids
        else "各行主键只有在该行需要被块表或明细行表挂接时才填"
    )
    recommended = "；".join(
        f"{sheet.name} 的 {_format_column_list(sheet, plain_required_oids(sheet))}"
        for sheet in chain
        if sheet is not analysis_sheet and plain_required_oids(sheet)
    )
    a9_rows_sheet = next(
        (
            sheet.name
            for sheet in layout.sheets
            if sheet.kind is SheetKind.GROUP and "A9" in sheet.host_oids
        ),
        "含 A9 的明细行表",
    )
    return {
        "minimal_analysis": minimal_analysis,
        "minimal_ratio": minimal_ratio,
        "pk_note": pk_note,
        "other_sheet_count": str(max(0, len(layout.entry_sheets) - 2)),
        "recommended": recommended or "（无）",
        "a9_rows_sheet": a9_rows_sheet,
    }


def readme_lines(layout: WorkbookLayout, profile: Profile) -> list[tuple[str, Font]]:
    """README 文本 → ``(行, 字体)``；模板里以 ``# `` 开头的是小节标题。"""
    block_sheets = [sheet.name for sheet in layout.sheets if sheet.kind is SheetKind.BLOCK]
    row_sheets = [sheet.name for sheet in layout.sheets if sheet.kind is SheetKind.GROUP]
    ratio_host_sheet = next(
        (sheet for sheet in layout.sheets if RATIO_HOST_COLUMN in sheet.helper_columns), None
    )
    ratio_hosts = (
        list(ratio_host_sheet.host_oids) if ratio_host_sheet else list(FALLBACK_RATIO_HOSTS)
    )
    text = README_TEMPLATE.format(
        source=PROFILE_SOURCE,
        version=profile.version,
        license=PROFILE_LICENSE,
        blocks="、".join(block_sheets) or "（无）",
        owner_sheets="、".join(owner_sheet_options(layout)),
        row_count=len(row_sheets),
        ratio_hosts="；".join(
            f"{oid} = {RATIO_HOST_LABELS.get(oid, '档案内联 B6 的宿主字段')}"
            for oid in ratio_hosts
        ),
        **_minimal_entry_text(layout, profile),
    )
    rendered: list[tuple[str, Font]] = []
    for index, line in enumerate(text.splitlines()):
        if index == 0:
            rendered.append((line, _TITLE_FONT))
        elif line.startswith("# "):
            rendered.append((line[2:], _SECTION_FONT))
        else:
            rendered.append((line, _BODY_FONT))
    return rendered


def write_readme_sheet(worksheet: Worksheet, layout: WorkbookLayout, profile: Profile) -> None:
    """写 `README` 使用说明表。"""
    worksheet.column_dimensions["A"].width = 118
    for index, (text, font) in enumerate(readme_lines(layout, profile), start=1):
        cell = worksheet.cell(row=index, column=1, value=text)
        cell.font = font
        cell.alignment = _TOP_ALIGN
    worksheet.freeze_panes = "A2"


__all__ = [
    "CHECK_WIDTHS",
    "FALLBACK_RATIO_HOSTS",
    "HEADER_FILL",
    "HEADER_FONT",
    "OWNER_SHEET_LIST_NAME",
    "RATIO_HOST_LABELS",
    "RATIO_NAME_LIST_NAME",
    "README_TEMPLATE",
    "SCHEMA_HEADERS",
    "SCHEMA_WIDTHS",
    "VOCAB_FIRST_DATA_ROW",
    "chain_entity_sheets",
    "group_condition_oid",
    "plain_required_oids",
    "readme_lines",
    "schema_rows",
    "unconditional_required_oids",
    "write_check_sheet",
    "write_readme_sheet",
    "write_schema_sheet",
    "write_vocab_sheet",
]
